{% set name = "copernicusmarine" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/copernicusmarine-{{ version }}.tar.gz
  sha256: b279ae3ac9e6c832d98eb4cf55bd2a167782d5ec695df70dc7e015cdddea631c

build:
  entry_points:
    - copernicusmarine = copernicusmarine.command_line_interface.copernicus_marine:command_line_interface
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core
    - pip
  run:
    - python >=3.9
    - click >=8.0.4
    - requests >=2.27.1
    - setuptools >=68.2.2
    - xarray >=2023.4.0
    - tqdm >=4.65.0
    - zarr >=2.13.3,<3.0.0
    - dask-core >=2022
    - boto3 >=1.26
    - semver >=3.0.2
    - pystac >=1.8.3
    - lxml >=4.9.0
    - numpy >=1.23.0
    - pydantic >=2.9.1,<3.0.0
    - h5netcdf >=1.4.0,<2.0.0

test:
  imports:
    - copernicusmarine
  commands:
    - pip check
    - copernicusmarine --help
  requires:
    - pip

about:
  home: https://help.marine.copernicus.eu/en/collections/4060068-copernicus-marine-toolbox
  summary: 'A command line and python interface to explore and download all the products provided by the Copernicus Marine Data Store without quotas'
  license: EUPL-1.2
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - slim0
    - nitreb
    - renaudjester
    - uriii3
    - jordi-domingo
