{% set name = "copernicusmarine" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/copernicusmarine-{{ version }}.tar.gz
  sha256: 093c329eb8b135a501e86ddd235283613002b60c1fc7523d7ea87865a6fc50f9

build:
  entry_points:
    - copernicusmarine = copernicusmarine.command_line_interface.copernicus_marine:command_line_interface
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.0.4,!=8.2.0
    - requests >=2.27.1
    - setuptools >=68.2.2
    - xarray >=2023.4.0
    - tqdm >=4.65.0
    - zarr >=2.13.3
    - dask-core >=2022
    - boto3 >=1.26
    - semver >=3.0.2
    - pystac >=1.8.3
    - numpy >=1.23.0
    - pydantic >=2.9.1,<3.0.0
    - h5netcdf >=1.4.0,<2.0.0
    - arcosparse >=0.4.0,<0.5.0

test:
  imports:
    - copernicusmarine
  commands:
    - pip check
    - copernicusmarine --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://help.marine.copernicus.eu/en/collections/4060068-copernicus-marine-toolbox
  summary: 'A command line and python interface to explore and download all the products provided by the Copernicus Marine Data Store without quotas'
  license: EUPL-1.2
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - slim0
    - nitreb
    - renaudjester
    - uriii3
    - jordi-domingo
    - Theophile-Varnier
