{% set name = "copernicusmarine" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/copernicusmarine-{{ version }}.tar.gz
  sha256: 999ed7c3cf50418f3e934a693a4e0400115f72f162350589d58cd91a4ffe404d

build:
  entry_points:
    - copernicusmarine = copernicusmarine.command_line_interface.copernicus_marine:command_line_interface
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core
    - pip
  run:
    - python >=3.9,<3.13
    - click >=8.0.4
    - requests >=2.27.1
    - aiohttp >=3.8.5
    - setuptools >=68.2.2
    - motuclient >=1.8.4
    - cachier >=2.2.1
    - xarray >=2023.4.0
    - tqdm >=4.65.0
    - zarr >=2.13.3
    - pydap >=3.2.2
    - dask-core >=2022
    - netcdf4 >=1.5.4
    - boto3 >=1.25
    - semver >=3.0.2
    - nest-asyncio >=1.5.8
    - pystac >=1.8.3
    - lxml >=4.9.0

test:
  imports:
    - copernicusmarine
  commands:
    - pip check
    - copernicusmarine --help
  requires:
    - pip

about:
  home: https://help.marine.copernicus.eu/en/collections/4060068-copernicus-marine-toolbox
  summary: 'A command line and python interface to explore and download all the products provided by the Copernicus Marine Data Store without quotas'
  license: EUPL-1.2
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - slim0
    - nitreb
